networks:
  green:
    external: true
    name: ${STACK_NAME}-green

volumes:
  kavita-config:

services: 
  kavita:
    image: jvmilazz0/kavita:latest
    container_name: ${STACK_NAME}-kavita
    hostname: kavita
    restart: unless-stopped
    networks:
      - green
    volumes:
      - kavita-config:/kavita/config
      - ${EXTRA_MOUNT_ROOT}/kavita:/mnt:ro
    environment:
      TZ: "Europe/London"
    ports:
      - ${PORTS_KAVITA}:5000
