networks:
  green:
    external: true
    name: ${STACK_NAME}-green

volumes:
  qbt-config:

services:
  qbittorrent:
    container_name: ${STACK_NAME}-qbittorrent
    hostname: qbittorrent
    image: hotio/qbittorrent:latest
    restart: unless-stopped
    environment:
      - WEBUI_PORTS=8080/tcp,8080/udp
      - TZ=Europe/London
    networks:
      - green
    ports:
      - ${PORTS_QBITTORRENT}:8080
    volumes:
      - qbt-config:/config
      - ${QBT_MOUNT_POINT}/torrents:/downloads
      - ${QBT_MOUNT_POINT}/media:/media

