volumes:
  joplin-data:

networks:
  green:
    external: true
    name: ${STACK_NAME}-green

services:
    db:
        image: postgres:16
        container_name: ${STACK_NAME}-joplin-db
        volumes:
          - joplin-data:/var/lib/postgresql/data
        ports:
          - "5432:5432"
        networks:
          - green
        restart: unless-stopped
        environment:
          - POSTGRES_PASSWORD=${JOPLIN_POSTGRES_PASSWORD}
          - POSTGRES_USER=joplin
          - POSTGRES_DB=joplin
    app:
        image: joplin/server:latest
        container_name: ${STACK_NAME}-joplin
        depends_on:
          - db
        networks:
          - green
        ports:
          - "22300:22300"
        restart: unless-stopped
        environment:
          - APP_PORT=22300
          - APP_BASE_URL=https://${SUBDOMAIN_JOPLIN}.${DOMAIN}
          - DB_CLIENT=pg
          - POSTGRES_PASSWORD=${JOPLIN_POSTGRES_PASSWORD}
          - POSTGRES_DATABASE=joplin
          - POSTGRES_USER=joplin
          - POSTGRES_PORT=joplin
          - POSTGRES_HOST=db

