networks:
  green:
    external: true
    name: ${STACK_NAME}-green

services:
    db:
        container_name: ${STACK_NAME}-joplin-db 
        image: postgres:15
        volumes:
            - ${JOPLIN_DB_MOUNT_POINT}:/var/lib/postgresql/data
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=${JOPLIN_POSTGRES_PASSWORD}
            - POSTGRES_USER=postgres
            - POSTGRES_DB=joplin
    app:
        container_name: ${STACK_NAME}-joplin 
        image: joplin/server:latest
        depends_on:
            - db
        ports:
            - ${PORTS_NOTES}:22300
        restart: unless-stopped
        environment:
            - APP_PORT=22300
            - APP_BASE_URL=https://notes.27hs.co.uk
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=${JOPLIN_POSTGRES_PASSWORD}
            - POSTGRES_DATABASE=joplin
            - POSTGRES_USER=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=db
            - MAILER_ENABLED=1
            - MAILER_HOST=smtp.gmail.com
            - MAILER_PORT=465
            - MAILER_SECURE=1
            - MAILER_AUTH_USER=${SMTP_USER}
            - MAILER_AUTH_PASSWORD=${SMTP_PASSWORD}
            - MAILER_NOREPLY_NAME=${SMTP_NAME}
            - MAILER_NOREPLY_EMAIL=${SMTP_FROM}
