version: "3.8"

networks:
  green:
    name: ${STACK_NAME}-green
    external: true

services:
  heimdall:
    image: linuxserver/heimdall
    container_name: ${STACK_NAME}-heimdall
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
    networks:
      - green
    ports:
      - "${PORTS_HOMEPAGE}:80"
    volumes:
      - ${HEIMDALL_MOUNT_POINT}:/config
    restart: unless-stopped

