networks:
  green:
    external: true
    name: ${STACK_NAME}-green

volumes:
  heimdall-user1-config:
  heimdall-user2-config:
  heimdall-user3-config:

services:
  heimdall-user1:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: ${STACK_NAME}-heimdall-user1
    hostname: heimdall-user1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - heimdall-user1-config:/config
    ports:
      - ${PORTS_USERDASH1}:80
    restart: unless-stopped

  heimdall-user2:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: ${STACK_NAME}-heimdall-user2
    hostname: heimdall-user2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - heimdall-user2-config:/config
    ports:
      - ${PORTS_USERDASH2}:80
    restart: unless-stopped

  heimdall-user3:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: ${STACK_NAME}-heimdall-user3
    hostname: heimdall-user3
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - heimdall-user3-config:/config
    ports:
      - ${PORTS_USERDASH3}:80
    restart: unless-stopped
