networks:
  green:
    external: true
    name: ${STACK_NAME}-green

volumes:
  fb-data:
  fb-config:      

services:
  app:
    container_name: ${STACK_NAME}-filebrowser
    hostname: filebrowser
    image: filebrowser/filebrowser
    restart: unless-stopped
    command:
      - sh
      - -c
      - >
        echo '{"port":80,"baseURL":"","address":"","log":"stdout","auth":{"method":"proxy","header":"X-Auth-User"},"branding":{"name":"FileBrowser"},"filesystem":{"root":"/srv"}}' > /.filebrowser.json &&
        

      #filebrowser -c /.filebrowser.json
    networks:
      - green
    ports:
      - ${PORTS_FILEBROWSER}:80
    volumes:
      - fb-data:/database
      - fb-config:/config
      - ${EXTRA_MOUNT_ROOT}:/srv:ro

