networks:
  green:
    external: true
    name: ${STACK_NAME}-green

volumes:
  fb-data:
  fb-config:      

services:
  app:
    container_name: ${STACK_NAME}-filebrowser
    hostname: filebrowser
    image: filebrowser/filebrowser
    restart: unless-stopped
    command: ["filebrowser config set --auth.method=proxy --auth.header=X-Preferred-Username"]
    networks:
      - green
    ports:
      - ${PORTS_FILEBROWSER}:80
    volumes:
      - fb-data:/database
      - fb-config:/config
      - ${EXTRA_MOUNT_ROOT}:/srv:ro

