volumes:
  data:
  config:

networks:
  green:
    external: true
    name: ${STACK_NAME}-green

services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: ${STACK_NAME}-openldap
    hostname: openldap
    domainname: ${OPENLDAP_DOMAIN}
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: ${OPENLDAP_ORGANISATION}
      LDAP_DOMAIN: ${OPENLDAP_DOMAIN}
      LDAP_BASE_DN: ${OPENLAP_BASE_DN}
      LDAP_ADMIN_PASSWORD: ${OPENLDAP_ADMIN_PASSWORD}
      LDAP_CONFIG_PASSWORD: ${OPENLDAP_CONFIG_PASSWORD}
      LDAP_READONLY_USER: "false"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      KEEP_EXISTING_CONFIG: ${OPENLDAP_KEEP_EXISTING_CONFIG}
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - data:/var/lib/ldap
      - config:/etc/ldap/slapd.d
      - /docker/${STACK_NAME}/certs:/container/service/slapd/assets/certs/
    networks:
      - green
    restart: always

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: ${STACK_NAME}-phpldapadmin
    hostname: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap 
      PHPLDAPADMIN_HTTPS: false 
    networks:
      - green
    ports:
      - "${PORTS_PHPLDAPADMIN}:80"
    depends_on:
      - openldap
    restart: unless-stopped
