networks:
  green:
    external: true
    name: ${STACK_NAME}-green

volumes:
  grist-data:

services:
  grist:
    container_name: ${STACK_NAME}-grist
    hostname: grist
    image: gristlabs/grist:latest
    networks:
      - green
    volumes:
      - grist-data:/persist
    ports:
      - ${PORTS_DATA}:8484
    environment:
      APP_HOME_URL: https://data.27hs.co.uk
      GRIST_SESSION_SECRET: ${GRIST_SESSION_SECRET}
      GRIST_DEFAULT_EMAIL: admin@27hs.co.uk
      GRIST_OIDC_IDP_ISSUER: ${GRIST_OIDC_ISSUER}
      GRIST_OIDC_IDP_CLIENT_ID: ${GRIST_OIDC_CLIENT_ID}
      GRIST_OIDC_IDP_CLIENT_SECRET: ${GRIST_OIDC_CLIENT_SECRET}
      GRIST_OIDC_IDP_SCOPES: openid email profile
      GRIST_OIDC_SP_HOST: https://data.27hs.co.uk
      GRIST_OIDC_IDP_SKIP_END_SESSION_ENDPOINT: true
