networks:
  green:
    external: true
    name: ${STACK_NAME}-green

volumes:
  gitea-data:
  gitea-pg-data:

services:
  gitea:
    image: gitea/gitea:latest
    container_name: ${STACK_NAME}-gitea
    hostname: gitea
    restart: unless-stopped
    networks:
      - green
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${PORTS_GITEA}:3000
      - ${PORTS_GITEA_SSH}:22
    environment:
      DISABLE_REGISTRATION: true
        #USER_UID: ${GITEA_USER_UID}
        #USER_GID: ${GITEA_USER_GID}
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: gitea-pg:5432
      GITEA__database__NAME: gitea
      GITEA__database__USER: gitea
      GITEA__database__PASSWD: ${GITEA_POSTGRES_PASSWORD}
        #GITEA__server__START_SSH_SERVER='true'
        #GITEA__server__SSH_PORT='3031'
        #GITEA__server__SSH_LISTEN_PORT='3031'

    depends_on:
      - gitea-pg

  gitea-pg:
    image: postgres:14
    container_name: ${STACK_NAME}-gitea-pg
    hostname: gitea-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: gitea
      POSTGRES_DB: gitea
      POSTGRES_PASSWORD: ${GITEA_POSTGRES_PASSWORD}
    networks:
      - green
    volumes:
      - gitea-pg-data:/var/lib/postgresql/data
