services:
  wireguard:
    image: linuxserver/wireguard
    container_name: ${STACK_NAME}-wireguard
    hostname: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    privileged: true
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - "${WG_PORT}:${WG_PORT}/udp"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SERVERURL=${DOMAIN}
      - SERVERPORT=${WG_PORT}
      - PEERS=1 # bootstrap config only
      - PEERDNS=auto
      - INTERNAL_SUBNET=${WG_SUBNET}
      - PERSISTENTKEEPALIVE_PEERS=all
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules:ro