networks:
  green:
    external: true
    name: ${STACK_NAME}-green

volumes:
  paperless-data:
  paperless-media:
  paperless-pg-data:
  paperless-redis-data:

services:
  paperless-redis:
    image: docker.io/library/redis:7
    container_name: ${STACK_NAME}-paperless-redis
    hostname: paperless-redis
    restart: unless-stopped
    networks:
      - green

  paperless-pg:
    image: docker.io/library/postgres:15
    container_name: ${STACK_NAME}-paperless-pg
    hostname: paperless-pg
    restart: unless-stopped
    networks:
      - green
    volumes:
      - ${PAPERLESS_MOUNT_ROOT}/pgsql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: ${PAPERLESS_POSTGRES_PASSWORD}

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.13.5
    container_name: ${STACK_NAME}-paperless
    hostname: paperless
    restart: unless-stopped
    depends_on:
      - paperless-redis
      - paperless-pg
    environment:
      PAPERLESS_URL: https://${SUBDOMAIN_PAPERLESS}.${DOMAIN}
      PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY}
      PAPERLESS_REDIS: redis://paperless-redis:6379
      PAPERLESS_DBHOST: paperless-pg
      PAPERLESS_DBPASS: ${PAPERLESS_POSTGRES_PASSWORD}
      PAPERLESS_APPS: "allauth.socialaccount.providers.openid_connect"
      PAPERLESS_SOCIALACCOUNT_PROVIDERS: |
        {
          "openid_connect": {
            "APPS": [
              {
                "provider_id": "synology",
                "name": "SSO",
                "client_id": "${PAPERLESS_CLIENT_ID}",
                "secret": "${PAPERLESS_CLIENT_SECRET}",
                "settings": {
                  "server_url": "https://${SUBDOMAIN_SSO}.${DOMAIN}/webman/sso/.well-known/openid-configuration"
                }
              }
            ]
          }
        }
      PAPERLESS_DISABLE_REGULAR_LOGIN: ${PAPERLESS_DISABLE_REGULAR_LOGIN}
    networks:
      - green
    ports:
      - ${PORTS_PAPERLESS}:8000
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 2m
      timeout: 10s
      retries: 5
    volumes:
      - ${PAPERLESS_MOUNT_ROOT}/data:/usr/src/paperless/data
      - ${PAPERLESS_MOUNT_ROOT}/media:/usr/src/paperless/media
        #- ./export:/usr/src/paperless/export
        #- ./consume:/usr/src/paperless/consume

