volumes:
  data:
    name: ${STACK_NAME}-android-data

services:
  android: 
    container_name: ${STACK_NAME}-android
    image: budtmo/docker-android:emulator_11.0
    devices:
      - /dev/kvm:/dev/kvm
    environment:
      - EMULATOR_DEVICE="Samsung Galaxy S10"
      - WEB_VNC=true
    ports:
      - ${PORTS_ANDROID}:6080
    volumes:
      data:/home/androidusr
