networks:
  green:
    external: true
    name: ${STACK_NAME}-green

volumes:
  homepage_config:

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: ${STACK_NAME}-homepage
    hostname: homepage
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_ALLOWED_HOSTS}
    ports:
      - ${PORTS_HOMEPAGE}:3000
    volumes:
      - ${HOMEPAGE_MOUNT_POINT}:/app/config
