networks:
  green:
    external: true
    name: ${STACK_NAME}-green

volumes:
  homepage_config:

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: ${STACK_NAME}-homepage
    hostname: homepage
    ports:
      - ${PORTS_HOMEPAGE}:3000
    volumes:
      - homepage_config:/app/config
