networks:
  green:
    external: true
    name: ${STACK_NAME}-green

volumes:
  homarr-appdata:

services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - homarr-appdata:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=${HOMARR_SECRET_ENCRYPTION_KEY}
      - AUTH_PROVIDERS=credentials,oidc
    ports:
      - ${PORTS_HOMARR}:7575
