services:
  db:
    image: postgres:15
    container_name: ${STACK_NAME}-kitchenowl-db
    environment:
      POSTGRES_DB: kitchenowl
      POSTGRES_USER: kitchenowl
      POSTGRES_PASSWORD: ${KITCHENOWL_POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  kitchenowl:
    image: tombursch/kitchenowl:latest
    container_name: ${STACK_NAME}-kitchenowl
    depends_on:
      - db
    ports:
      - ${PORTS_KITCHENOWL}:8080
    environment:
      FRONT_URL: https://food.27hs.co.uk
      JWT_SECRET_KEY: ${KITCHENOWL_JWT_SECRET_KEY}

      # Database configuration
      DB_DRIVER: postgresql
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: kitchenowl
      DB_PASSWORD: ${KITCHENOWL_POSTGRES_PASSWORD}
      DB_NAME: kitchenowl

      # OIDC (OpenID Connect) configuration
      ENABLE_OIDC: "true"
      OIDC_CLIENT_ID: ${KITCHENOWL_OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${KITCHENOWL_OIDC_CLIENT_SECRET}
      OIDC_ISSUER: https://auth.27hs.co.uk/webman/sso/

      LLM_MODEL: ${KITCHENOWL_LLM_MODEL}
      OPENAI_API_KEY: ${KITCHENOWL_OPENAI_API_KEY}

    restart: unless-stopped

volumes:
  db_data:

