networks:
  green:
    external: true
    name: ${STACK_NAME}-green

volumes:
  jellyfin-config:
  jellyfin-cache:

services:
  jellyfin:
    image: jellyfin/jellyfin:10.10.6
    container_name: ${STACK_NAME}-jellyfin
    hostname: jellyfin
    networks:
      - green
    ports:
      - ${PORTS_JELLYFIN}:8096
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - ${JELLYFIN_MOUNT_POINT}:/mnt/library
    restart: unless-stopped
    environment:
      - JELLYFIN_PublishedServerUrl=https://${SUBDOMAIN_JELLYFIN}.${DOMAIN}
