networks:
  green:
    external: true
    name: ${STACK_NAME}-green

volumes:
  fb-data:
  fb-config:      

services:
  app:
    container_name: ${STACK_NAME}-filebrowser
    hostname: filebrowser
    image: filebrowser/filebrowser
    restart: unless-stopped
      #environment:
    networks:
      - green
    ports:
      - ${PORTS_FILEBROWSER_HTTP}:80
    volumes:
      - fb-data:/database
      - fb-config:/config
      - ${FILEBROWSER_ROOT_FOLDER}:/srv:ro
    deploy:
      replicas: 0

