networks:
  green:
    external: true
    name: ${STACK_NAME}-green

volumes:
    filestash: {}

services:
  app:
    container_name: ${STACK_NAME}-filestash
    hostname: filestash
    image: machines/filestash
    restart: always
    environment:
    - APPLICATION_URL=https://files.27hs.co.uk
      #- GDRIVE_CLIENT_ID=<gdrive_client>
      #- GDRIVE_CLIENT_SECRET=<gdrive_secret>
      #- DROPBOX_CLIENT_ID=<dropbox_key>
    - ONLYOFFICE_URL=http://filestash-oods
    networks:
      - green
    ports:
    - ${PORTS_FILESTASH_HTTP}:8334
    volumes:
    - filestash:/app/data/state/
    - /docker/27hs/vol:/mnt/vol

  onlyoffice:
    container_name: ${STACK_NAME}-filestash-oods
    hostname: filestash-oods
    image: onlyoffice/documentserver:7.1
    restart: always
