networks:
  green:
    external: true
    name: ${STACK_NAME}-green

volumes:
  fb-data:
  fb-config:      

services:
  app:
    container_name: ${STACK_NAME}-filebrowser
    hostname: filebrowser
    image: hurlenko/filebrowser
    restart: unless-stopped
    environment:
      - FB_BASEURL="https://files.27hs.co.uk"
    networks:
      - green
    ports:
      - ${PORTS_FILEBROWSER_HTTP}:8080
    volumes:
      - fb-data:/data
      - fb-config:/config
      - /docker/27hs/mnt:/mnt:ro

