---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: 27HS Services

description: don't forget to feed the cat!

layout:
  Hosted Services:
    style: row
    columns: 3

providers:
  openweathermap: ca556924cf7fdcaef33f92759280a8ba
  weatherapi: weatherapiapikey
