networks:
  green:
    external: true
    name: ${STACK_NAME}-green

volumes:
  glance_config:

services:
  glance:
    image: glanceapp/glance
    container_name: ${STACK_NAME}-glance
    hostname: glance
    command: >
      sh -c "ln -s /extra/glance.yml /app/glance.yml
          && ln -s /extra/logo.png /app/assets/logo.png"
    networks:
      - green
    ports:
      - ${PORT_GLANCE}:8080
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - glance_config:/extra
